"""
Analyze Serial Number Patterns from Supabase Records
This script fetches all scans and analyzes serial number patterns per part ID
to determine the correct number of digits after the last letter for each product.

Usage:
    python analyze_serial_patterns.py
"""

import os
import re
from collections import defaultdict
from typing import Dict, List, Tuple

try:
    from supabase import create_client, Client
except ImportError:
    print("Error: Missing 'supabase' package")
    print("Run: pip install supabase")
    exit(1)

# Supabase Configuration
SUPABASE_URL = "https://ospedluufxgpfvqtznej.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zcGVkbHV1ZnhncGZ2cXR6bmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5ODgyMTUsImV4cCI6MjA4MTU2NDIxNX0.1AhtuANYs-eVrQIdW9gqt_KLhBxF4Vm0j6pqtrrJAag"


def count_digits_after_last_letter(serial: str) -> int:
    """
    Count the number of digits after the last letter in a serial number.
    Examples:
        'PUL9000K29498' -> 5 (digits: 29498 after K)
        'MGCK173156' -> 6 (digits: 173156 after K)
        'R757WM102689' -> 6 (digits: 102689 after M)
        '757EN11203' -> 5 (digits: 11203 after N)
    """
    if not serial:
        return 0

    # Find last letter position
    match = re.search(r"[A-Z]([0-9]*)$", serial)
    if match:
        return len(match.group(1))

    return 0


def get_serial_prefix(serial: str) -> str:
    """
    Extract the serial prefix (everything before the trailing digits).
    Examples:
        'PUL9000K29498' -> 'PUL9000K'
        'MGCK173156' -> 'MGCK'
        'R757WM102689' -> 'R757WM'
    """
    if not serial:
        return ""

    match = re.match(r"^(.+?)(\d+)$", serial)
    if match:
        return match.group(1)

    return serial


def analyze_part_serials(part_id: str, serials: List[str]) -> Dict:
    """
    Analyze serial numbers for a specific part ID.
    Returns statistics about digit patterns.
    """
    if not serials:
        return None

    digit_counts = []
    prefixes = defaultdict(int)

    for serial in serials:
        digits = count_digits_after_last_letter(serial)
        prefix = get_serial_prefix(serial)

        digit_counts.append(digits)
        prefixes[prefix] += 1

    # Calculate statistics
    unique_counts = sorted(set(digit_counts))
    most_common_count = (
        max(set(digit_counts), key=digit_counts.count) if digit_counts else 0
    )
    most_common_prefix = (
        max(prefixes.items(), key=lambda x: x[1]) if prefixes else ("", 0)
    )

    # Check if data is consistent (all serials have same digit count)
    is_consistent = len(unique_counts) == 1

    return {
        "part_id": part_id,
        "total_records": len(serials),
        "digit_counts": unique_counts,
        "most_common_count": most_common_count,
        "most_common_prefix": most_common_prefix[0],
        "is_consistent": is_consistent,
        "unique_prefixes": len(prefixes),
        "example_serials": serials[:5],  # First 5 examples
    }


def fetch_all_scans(client: Client) -> List[Dict]:
    """
    Fetch all scans from Supabase with pagination.
    """
    print("Fetching all scans from Supabase...")

    all_scans = []
    page = 0
    page_size = 1000
    has_more = True

    while has_more:
        start = page * page_size
        end = start + page_size - 1

        response = client.table("scans").select("*").range(start, end).execute()

        if response.data and len(response.data) > 0:
            all_scans.extend(response.data)
            page += 1
            has_more = len(response.data) == page_size
            print(f"  Fetched {len(response.data)} records (total: {len(all_scans)})")
        else:
            has_more = False

        # Safety limit
        if page > 50:
            print("  Warning: Reached safety limit (50,000 records)")
            break

    return all_scans


def generate_product_rules(part_analysis: Dict[str, Dict]) -> str:
    """
    Generate JavaScript code for PRODUCT_SERIAL_RULES based on analysis.
    """
    js_lines = [
        "// ===== PRODUCT-SPECIFIC SERIAL EXTRACTION RULES =====",
        "// Generated by analyze_serial_patterns.py based on actual data",
        "// Maps product codes to specific serial number extraction patterns",
        "",
        "const PRODUCT_SERIAL_RULES = {",
    ]

    # Sort by part ID
    sorted_parts = sorted(part_analysis.keys())

    for part_id in sorted_parts:
        analysis = part_analysis[part_id]

        # Only include consistent patterns
        if not analysis["is_consistent"]:
            js_lines.append(
                f"    // {part_id}: SKIPPED - Inconsistent digit counts: {analysis['digit_counts']}"
            )
            continue

        # Only include parts with digit counts
        count = analysis["most_common_count"]
        if count == 0:
            js_lines.append(f"    // {part_id}: SKIPPED - No trailing digits found")
            continue

        prefix = analysis["most_common_prefix"]
        # Escape backslashes for JavaScript regex
        escaped_prefix = prefix.replace("\\", "\\\\")
        js_lines.append(f"    '{part_id}': {{")
        js_lines.append(f"        pattern: /^(\\{escaped_prefix}\\d{{{count}}}).*$/,")
        js_lines.append(f"        extractGroup: 1,")
        js_lines.append(
            f"        description: 'Extract full {prefix} + {count} digits, ignore trailing check digits/padding'"
        )
        js_lines.append(f"    }},")

    js_lines.append("};")

    # Add comment for manual review
    js_lines.append("")
    js_lines.append("// ===== MANUAL REVIEW REQUIRED =====")
    js_lines.append("// Parts with inconsistent patterns (verify correct digit count):")
    js_lines.append("//")

    inconsistent_parts = [
        (pid, part_analysis[pid])
        for pid in sorted_parts
        if not part_analysis[pid]["is_consistent"]
        or part_analysis[pid]["most_common_count"] == 0
    ]

    for part_id, analysis in inconsistent_parts:
        js_lines.append(f"// {part_id}:")
        js_lines.append(f"//   Total records: {analysis['total_records']}")
        js_lines.append(f"//   Digit counts found: {analysis['digit_counts']}")
        js_lines.append(f"//   Most common: {analysis['most_common_count']} digits")
        js_lines.append(f"//   Unique prefixes: {analysis['unique_prefixes']}")
        js_lines.append(f"//   Examples: {', '.join(analysis['example_serials'][:3])}")
        js_lines.append("//")

    return "\n".join(js_lines)


def main():
    print("\n" + "=" * 60)
    print("SERIAL NUMBER PATTERN ANALYSIS")
    print("=" * 60 + "\n")

    # Initialize Supabase client
    print("Connecting to Supabase...")
    client = create_client(SUPABASE_URL, SUPABASE_KEY)

    # Fetch all scans
    scans = fetch_all_scans(client)
    print(f"\nTotal records fetched: {len(scans)}")

    # Group by part ID
    part_serials = defaultdict(list)
    for scan in scans:
        part_id = scan.get("part_id") or "UNKNOWN"
        serial = scan.get("serial_number") or ""

        if serial:  # Only include records with serial numbers
            part_serials[part_id].append(serial)

    print(f"Unique part IDs found: {len(part_serials)}\n")

    # Analyze each part
    print("Analyzing serial patterns per part ID...")
    print("-" * 60)

    part_analysis = {}
    for part_id in sorted(part_serials.keys()):
        serials = part_serials[part_id]
        analysis = analyze_part_serials(part_id, serials)
        part_analysis[part_id] = analysis

        # Print analysis
        consistent_mark = "OK" if analysis["is_consistent"] else "WARN"
        print(f"[{consistent_mark}] {part_id}")
        print(f"    Records: {analysis['total_records']}")
        print(f"    Digit counts: {analysis['digit_counts']}")
        print(f"    Most common: {analysis['most_common_count']} digits")
        print(f"    Most common prefix: {analysis['most_common_prefix']}")
        print(f"    Unique prefixes: {analysis['unique_prefixes']}")
        print(f"    Examples: {', '.join(analysis['example_serials'][:3])}")
        print()

    # Generate summary
    print("-" * 60)
    consistent_parts = [
        pid
        for pid, analysis in part_analysis.items()
        if analysis["is_consistent"] and analysis["most_common_count"] > 0
    ]
    inconsistent_parts = [
        pid
        for pid, analysis in part_analysis.items()
        if not analysis["is_consistent"] or analysis["most_common_count"] == 0
    ]

    print(f"\nSUMMARY:")
    print(f"  Total part IDs: {len(part_analysis)}")
    print(f"  Consistent patterns (auto-rule-ready): {len(consistent_parts)}")
    print(f"  Inconsistent patterns (manual review): {len(inconsistent_parts)}")

    # Generate JavaScript rules
    print("\n" + "=" * 60)
    print("GENERATING PRODUCT_SERIAL_RULES")
    print("=" * 60 + "\n")

    js_rules = generate_product_rules(part_analysis)

    # Output to console
    print(js_rules)

    # Save to file
    output_file = "product_rules_generated.js"
    with open(output_file, "w") as f:
        f.write(js_rules)

    print(f"\nRules saved to: {output_file}")
    print(f"\nNext steps:")
    print(f"  1. Review the generated rules in {output_file}")
    print(f"  2. Manually review inconsistent parts (marked with // SKIPPED)")
    print(f"  3. Copy the consistent rules to app.js PRODUCT_SERIAL_RULES")
    print()


if __name__ == "__main__":
    main()
