// ===== PRODUCT-SPECIFIC SERIAL EXTRACTION RULES =====
// Generated by analyze_serial_patterns.py based on actual data
// Maps product codes to specific serial number extraction patterns

const PRODUCT_SERIAL_RULES = {
    '100752EL': {
        pattern: /^(\752EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 752EL + 5 digits, ignore trailing check digits/padding'
    },
    '100752EW': {
        pattern: /^(\752EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 752EW + 5 digits, ignore trailing check digits/padding'
    },
    '100752WKW': {
        pattern: /^(\752WKN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 752WKN + 5 digits, ignore trailing check digits/padding'
    },
    '100756E2': {
        pattern: /^(\756E\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full 756E + 6 digits, ignore trailing check digits/padding'
    },
    '100756EL': {
        pattern: /^(\756EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 756EL + 5 digits, ignore trailing check digits/padding'
    },
    // 100756EW: SKIPPED - Inconsistent digit counts: [0, 5]
    // 100756NW: SKIPPED - Inconsistent digit counts: [5, 6]
    '100757E2': {
        pattern: /^(\757E\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full 757E + 6 digits, ignore trailing check digits/padding'
    },
    // 100757EL: SKIPPED - Inconsistent digit counts: [5, 6]
    // 100757EN: SKIPPED - Inconsistent digit counts: [5, 6]
    // 100757EW: SKIPPED - Inconsistent digit counts: [5, 6]
    '100757NKNW': {
        pattern: /^(\757NKNW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 757NKNW + 5 digits, ignore trailing check digits/padding'
    },
    '100757NW': {
        pattern: /^(\757NW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 757NW + 5 digits, ignore trailing check digits/padding'
    },
    // 100758EL: SKIPPED - Inconsistent digit counts: [5, 6]
    '100758EW': {
        pattern: /^(\758EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 758EW + 5 digits, ignore trailing check digits/padding'
    },
    '100758NKNW': {
        pattern: /^(\758NKNW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 758NKNW + 5 digits, ignore trailing check digits/padding'
    },
    '100758NW': {
        pattern: /^(\758NW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 758NW + 5 digits, ignore trailing check digits/padding'
    },
    '100759E2': {
        pattern: /^(\759E\d{7}).*$/,
        extractGroup: 1,
        description: 'Extract full 759E + 7 digits, ignore trailing check digits/padding'
    },
    '100759EL': {
        pattern: /^(\759EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 759EL + 5 digits, ignore trailing check digits/padding'
    },
    '100759ELRN': {
        pattern: /^(\100759ELRN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 100759ELRN + 5 digits, ignore trailing check digits/padding'
    },
    '100759EW': {
        pattern: /^(\759EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 759EW + 5 digits, ignore trailing check digits/padding'
    },
    '100759NW': {
        pattern: /^(\759NW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 759NW + 5 digits, ignore trailing check digits/padding'
    },
    '100759WC': {
        pattern: /^(\759WC\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 759WC + 5 digits, ignore trailing check digits/padding'
    },
    // 100760: SKIPPED - No trailing digits found
    // 100760E: SKIPPED - Inconsistent digit counts: [5, 6]
    // 100760E2: SKIPPED - Inconsistent digit counts: [6, 7]
    // 100760EL: SKIPPED - Inconsistent digit counts: [4, 5, 6]
    // 100760ELN: SKIPPED - Inconsistent digit counts: [5, 6]
    '100760K': {
        pattern: /^(\760K\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 760K + 5 digits, ignore trailing check digits/padding'
    },
    '100760KN': {
        pattern: /^(\760KN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 760KN + 5 digits, ignore trailing check digits/padding'
    },
    '100780EL': {
        pattern: /^(\780EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 780EL + 5 digits, ignore trailing check digits/padding'
    },
    '100780EW': {
        pattern: /^(\780EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 780EW + 5 digits, ignore trailing check digits/padding'
    },
    '100780NKNW': {
        pattern: /^(\780NKNW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 780NKNW + 5 digits, ignore trailing check digits/padding'
    },
    '100780W': {
        pattern: /^(\780W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 780W + 5 digits, ignore trailing check digits/padding'
    },
    // 536713-001: SKIPPED - Inconsistent digit counts: [0, 5, 6]
    // 536713-002: SKIPPED - Inconsistent digit counts: [0, 5, 6, 7]
    '536713-002S': {
        pattern: /^(\MGC2S\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full MGC2S + 6 digits, ignore trailing check digits/padding'
    },
    '536713-004': {
        pattern: /^(\MGC4C\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full MGC4C + 5 digits, ignore trailing check digits/padding'
    },
    // 536713-005: SKIPPED - Inconsistent digit counts: [5, 6]
    // 536719-001: SKIPPED - Inconsistent digit counts: [0, 5, 6]
    '536719-001S': {
        pattern: /^(\MGCK1S\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full MGCK1S + 5 digits, ignore trailing check digits/padding'
    },
    // 536719-004: SKIPPED - Inconsistent digit counts: [5, 6]
    // 536723-001: SKIPPED - Inconsistent digit counts: [6, 7]
    // 756EL: SKIPPED - Inconsistent digit counts: [5, 6]
    '756EW': {
        pattern: /^(\R756EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R756EW + 5 digits, ignore trailing check digits/padding'
    },
    '756W': {
        pattern: /^(\R756W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R756W + 5 digits, ignore trailing check digits/padding'
    },
    '757E2': {
        pattern: /^(\R757E\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full R757E + 6 digits, ignore trailing check digits/padding'
    },
    '757EL': {
        pattern: /^(\R757EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R757EL + 5 digits, ignore trailing check digits/padding'
    },
    '757ELMSN': {
        pattern: /^(\R757ELMSN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R757ELMSN + 5 digits, ignore trailing check digits/padding'
    },
    '757EW': {
        pattern: /^(\R757EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R757EW + 5 digits, ignore trailing check digits/padding'
    },
    '757WM': {
        pattern: /^(\R757WM\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full R757WM + 6 digits, ignore trailing check digits/padding'
    },
    '757WMN': {
        pattern: /^(\R757WMN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R757WMN + 5 digits, ignore trailing check digits/padding'
    },
    '758EL': {
        pattern: /^(\R758EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R758EL + 5 digits, ignore trailing check digits/padding'
    },
    '758EW': {
        pattern: /^(\R758EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R758EW + 5 digits, ignore trailing check digits/padding'
    },
    '758W': {
        pattern: /^(\R758W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R758W + 5 digits, ignore trailing check digits/padding'
    },
    '758WM': {
        pattern: /^(\R758WM\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R758WM + 5 digits, ignore trailing check digits/padding'
    },
    '758WMN': {
        pattern: /^(\R758WMN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R758WMN + 5 digits, ignore trailing check digits/padding'
    },
    '759E2': {
        pattern: /^(\R759E\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full R759E + 6 digits, ignore trailing check digits/padding'
    },
    '759EL': {
        pattern: /^(\R759EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R759EL + 5 digits, ignore trailing check digits/padding'
    },
    // 759EW: SKIPPED - Inconsistent digit counts: [5, 6]
    '759WMN': {
        pattern: /^(\R759WMN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R759WMN + 5 digits, ignore trailing check digits/padding'
    },
    '760EL': {
        pattern: /^(\R760EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R760EL + 5 digits, ignore trailing check digits/padding'
    },
    '780EW': {
        pattern: /^(\R780EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R780EW + 5 digits, ignore trailing check digits/padding'
    },
    '790EL': {
        pattern: /^(\R790EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R790EL + 5 digits, ignore trailing check digits/padding'
    },
    '790W': {
        pattern: /^(\R790W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full R790W + 5 digits, ignore trailing check digits/padding'
    },
    '7EW1': {
        pattern: /^(\EBS757EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full EBS757EW + 5 digits, ignore trailing check digits/padding'
    },
    'EBS756NW': {
        pattern: /^(\EBS756NW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full EBS756NW + 5 digits, ignore trailing check digits/padding'
    },
    'EBS757EW': {
        pattern: /^(\EBS757EW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full EBS757EW + 5 digits, ignore trailing check digits/padding'
    },
    'EBS757NW': {
        pattern: /^(\EBS757NW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full EBS757NW + 5 digits, ignore trailing check digits/padding'
    },
    'EBS759EL': {
        pattern: /^(\EBS759EL\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full EBS759EL + 5 digits, ignore trailing check digits/padding'
    },
    'EBS780NW': {
        pattern: /^(\EBS780NW\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full EBS780NW + 5 digits, ignore trailing check digits/padding'
    },
    'FIL7958': {
        pattern: /^(\FIL\d{9}).*$/,
        extractGroup: 1,
        description: 'Extract full FIL + 9 digits, ignore trailing check digits/padding'
    },
    // P55541001: SKIPPED - No trailing digits found
    'P5554100E': {
        pattern: /^(\4100E\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 4100E + 5 digits, ignore trailing check digits/padding'
    },
    // P5556100: SKIPPED - No trailing digits found
    'P5556100E': {
        pattern: /^(\6100E\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 6100E + 5 digits, ignore trailing check digits/padding'
    },
    'P5556100E1': {
        pattern: /^(\6100E\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 6100E + 5 digits, ignore trailing check digits/padding'
    },
    'P5557100E': {
        pattern: /^(\7100E\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 7100E + 5 digits, ignore trailing check digits/padding'
    },
    'P5559100E': {
        pattern: /^(\9100E\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full 9100E + 5 digits, ignore trailing check digits/padding'
    },
    'PFR60W': {
        pattern: /^(\PFR60W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR60W + 5 digits, ignore trailing check digits/padding'
    },
    'PFR60WE2': {
        pattern: /^(\PFR60WE\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR60WE + 6 digits, ignore trailing check digits/padding'
    },
    'PFR60WK': {
        pattern: /^(\PFR60WK\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR60WK + 5 digits, ignore trailing check digits/padding'
    },
    'PFR70W': {
        pattern: /^(\PFR70W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR70W + 5 digits, ignore trailing check digits/padding'
    },
    // PFR70WE2N: SKIPPED - Inconsistent digit counts: [0, 5]
    'PFR80W': {
        pattern: /^(\PFR80W\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR80W + 5 digits, ignore trailing check digits/padding'
    },
    'PFR80WE2': {
        pattern: /^(\PFR80WE\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR80WE + 6 digits, ignore trailing check digits/padding'
    },
    'PFR80WKN': {
        pattern: /^(\PFR80WKN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR80WKN + 5 digits, ignore trailing check digits/padding'
    },
    'PFR80WN': {
        pattern: /^(\PFR80WN\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR80WN + 5 digits, ignore trailing check digits/padding'
    },
    'PFR8WE2': {
        pattern: /^(\PFR8WE\d{6}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR8WE + 6 digits, ignore trailing check digits/padding'
    },
    'PFR8WK': {
        pattern: /^(\PFR8WK\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PFR8WK + 5 digits, ignore trailing check digits/padding'
    },
    'PUL9000K': {
        pattern: /^(\PUL9000K\d{5}).*$/,
        extractGroup: 1,
        description: 'Extract full PUL9000K + 5 digits, ignore trailing check digits/padding'
    },
    'TNN102': {
        pattern: /^(\TNN\d{8}).*$/,
        extractGroup: 1,
        description: 'Extract full TNN + 8 digits, ignore trailing check digits/padding'
    },
};

// ===== MANUAL REVIEW REQUIRED =====
// Parts with inconsistent patterns (verify correct digit count):
//
// 100756EW:
//   Total records: 31
//   Digit counts found: [0, 5]
//   Most common: 5 digits
//   Unique prefixes: 2
//   Examples: 756EW15410, 756EW15411, 756EW15412
//
// 100756NW:
//   Total records: 87
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 756NW15257, 756NW15258, 756NW15235
//
// 100757EL:
//   Total records: 30
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 757EL12421, 757EL12407, 757EL12414
//
// 100757EN:
//   Total records: 11
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 757EN112025, 757EN112036, 757EN11204
//
// 100757EW:
//   Total records: 79
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 757EW24824, 757EW24825, 757EW24826
//
// 100758EL:
//   Total records: 13
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 758EL11421, 758EL11420, 758EL11422
//
// 100760:
//   Total records: 4
//   Digit counts found: [0]
//   Most common: 0 digits
//   Unique prefixes: 1
//   Examples: 76012641, 76012642, 76012643
//
// 100760E:
//   Total records: 24
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 760E13274, 760E13272, 760E13273
//
// 100760E2:
//   Total records: 9
//   Digit counts found: [6, 7]
//   Most common: 6 digits
//   Unique prefixes: 1
//   Examples: 760E210722, 760E210723, 760E2107152
//
// 100760EL:
//   Total records: 15
//   Digit counts found: [4, 5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 760EL12507, 760EL12508, 760EL12509
//
// 100760ELN:
//   Total records: 11
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: 760ELN10291, 760ELN10292, 760ELN10293
//
// 536713-001:
//   Total records: 43
//   Digit counts found: [0, 5, 6]
//   Most common: 5 digits
//   Unique prefixes: 4
//   Examples: MGC1S17774, MGC1S17760, MGC1S17761
//
// 536713-002:
//   Total records: 682
//   Digit counts found: [0, 5, 6, 7]
//   Most common: 6 digits
//   Unique prefixes: 7
//   Examples: MGC2S104117, MGC2S104118, MGC2S103972
//
// 536713-005:
//   Total records: 52
//   Digit counts found: [5, 6]
//   Most common: 6 digits
//   Unique prefixes: 2
//   Examples: MGC512175, MGC512176, MGC512177
//
// 536719-001:
//   Total records: 1774
//   Digit counts found: [0, 5, 6]
//   Most common: 6 digits
//   Unique prefixes: 8
//   Examples: MGCK173132, MGCK173133, MGCK173137
//
// 536719-004:
//   Total records: 8
//   Digit counts found: [5, 6]
//   Most common: 6 digits
//   Unique prefixes: 2
//   Examples: MGCK365005, MGCK365001, MGCK365006
//
// 536723-001:
//   Total records: 238
//   Digit counts found: [6, 7]
//   Most common: 7 digits
//   Unique prefixes: 2
//   Examples: MGCK2S114312, MGCK2S114313, MGCK2114212
//
// 756EL:
//   Total records: 30
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: R756EL11978, R756EL11979, R756EL11980
//
// 759EW:
//   Total records: 15
//   Digit counts found: [5, 6]
//   Most common: 5 digits
//   Unique prefixes: 1
//   Examples: R759EW12116, R759EW12117, R759EW12118
//
// P55541001:
//   Total records: 2
//   Digit counts found: [0]
//   Most common: 0 digits
//   Unique prefixes: 1
//   Examples: 410013027, 410013028
//
// P5556100:
//   Total records: 1
//   Digit counts found: [0]
//   Most common: 0 digits
//   Unique prefixes: 1
//   Examples: 61001263
//
// PFR70WE2N:
//   Total records: 4
//   Digit counts found: [0, 5]
//   Most common: 5 digits
//   Unique prefixes: 2
//   Examples: PFR70WE2N10967, PFR70WE2N10968, PFR70WE2N10971
//